### ISSUE TITLE
Unable to Connect to Saturn 3 Ultra, Lychee Connects Successfully

### ISSUE THREAD

**Issue by Allariah** [arsi-apli/UltraRemote#10]
Jan 13, 2024 4:21:56 P.M. sk.arsi.saturn.ultra.sender.mqtt.MqttServer run
SEVERE: null
java.net.SocketTimeoutException: Accept timed out
        at java.base/sun.nio.ch.NioSocketImpl.timedAccept(NioSocketImpl.java:713)
        at java.base/sun.nio.ch.NioSocketImpl.accept(NioSocketImpl.java:757)
        at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:675)
        at java.base/java.net.ServerSocket.platformImplAccept(ServerSocket.java:641)
        at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:617)
        at java.base/java.net.ServerSocket.implAccept(ServerSocket.java:574)
        at java.base/java.net.ServerSocket.accept(ServerSocket.java:532)
        at sk.arsi.saturn.ultra.sender.mqtt.MqttServer.run(MqttServer.java:114)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by arsi-apli** [comment]
If this exception occurs, at 99.9% the firewall blocks the incoming connection.
