### ISSUE TITLE
connection loss

### ISSUE THREAD

**Issue by steeveone** [arsi-apli/UltraRemote#12]
i can connect to printer but i loose connection after few seconds. Reinitialize Connection button doesn't have effect.
I also have the following exception when i select my printer: 

`Exception in thread "pool-1-thread-1" java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.databind.JsonNode.asInt()" because the return value of "com.fasterxml.jackson.databind.JsonNode.get(String)" is null
        at sk.arsi.saturn.ultra.sender.pojo.Attributes.AttrDeserializer.deserialize(AttrDeserializer.java:50)
        at sk.arsi.saturn.ultra.sender.pojo.Attributes.AttrDeserializer.deserialize(AttrDeserializer.java:29)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
        at sk.arsi.saturn.ultra.sender.mqtt.MqttServer.decodeMessage(MqttServer.java:264)
        at sk.arsi.saturn.ultra.sender.mqtt.MqttServer.run(MqttServer.java:148)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)`

If can help, i am using the last 1.5.4 firmware

**Comment by arsi-apli** [comment]
I think it's fixed with #14
